logging:
  level:
    org.springframework: INFO
    org.cowary.arttrackerback: INFO
  file:
    name: logs/app.log
spring:
  application:
    name: air-to-back
  datasource:
    url: ${db.url}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      schema: myne
      username: ${db.username}
      password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 25
  liquibase:
    enabled: true
app:
  shiki:
    base_url: https://shikimori.io/api
    anime.url: /animes
    manga.url: /mangas
    ranobe.url: /ranobe
    role.url: /roles
  kino:
    base_url: https://kinopoiskapiunofficial.tech
    token: ${kino.token}


